name: T00ls签到

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 16,1 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2
      # 安装 Python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: '安装 requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行t00ls签到脚本'  
        run: python3 T00ls_sign.py 
        env:
            # 用户名:  
            username: ${{ secrets.username }}
            # 明文密码或密码MD5:  
            password: ${{ secrets.password }}
            # 问题答案，没有可不填:  
            answer:   ${{ secrets.answer }}
            # Webhook加签秘钥:  
            secret_key : ${{ secrets.secret_key  }}
            # Webhook access_token
            access_token  : ${{ secrets.access_token   }}
            # Server酱申请的skey:  
            SCKEY:   ${{ secrets.SCKEY }}
